Repository ankitpokhrel/tus-php, pull requests merged in 2018-09, with the labels that each got.

#71 Add ability to load configs from file
  README.md
  phpunit.xml
  src/Cache/CacheFactory.php
  src/Cache/FileStore.php
  src/Cache/RedisStore.php
  src/Commands/ExpirationCommand.php
  src/Config.php
  src/Config/default.php
  src/Tus/Client.php
  tests/Cache/FileStoreTest.php
  tests/ConfigTest.php
  tests/Fixtures/config.php
  tests/bootstrap.php
Labels: defect, feature

#76 Remove cache dependency from Client
  README.md
  example/basic/upload.php
  example/basic/verify.php
  example/partial/partial.php
  src/Tus/Client.php
  tests/Tus/ClientTest.php
Labels: defect

#81 Fix Doc
  README.md
Labels: doc | suggestions
