Repository ankitpokhrel/tus-php, pull requests merged in 2018-10, with the labels that each got.

#87 Treat HEAD and GET as an identical request
  example/basic/index.php
  src/Tus/Server.php
  tests/Tus/ServerTest.php
Labels: improvement

#89 Remove unreachable code
  src/Tus/Server.php
  tests/Tus/ServerTest.php
Labels: improvement

#90 Accept all guzzle options in tus client
  src/Tus/Client.php
  tests/Tus/ClientTest.php
Labels: feature

#95 Add missing headers in client
  src/Tus/Client.php
  src/Tus/Server.php
  tests/Tus/ClientTest.php
  tests/Tus/ServerTest.php
Labels: client, defect

#98 [Issue fix/#96] Add missing checks in patch request #96
  src/Tus/AbstractTus.php
  src/Tus/Client.php
  src/Tus/Server.php
  tests/Tus/ServerTest.php
Labels: defect, server
