Repository ankitpokhrel/tus-php, pull requests merged in 2019-12, with the labels that each got.

#215 Update docker image to use php7.4 phpearth image
  docker/base/Dockerfile
  docker/base/configs/www.conf
  docker/client/configs/default.conf
  docker/server/configs/default.conf
Labels: improvement

#217 Upgrade symfony packages
  composer.json
Labels: dependencies

#220 dev: Install APCu extension
  docker/base/Dockerfile
  docker/base/configs/php.ini
Labels: dev

#221 ci: Enable APCu extension for PHP >= 7.3
  .travis.yml
Labels: dev/ci
