Repository ankitpokhrel/tus-php, pull requests merged in 2019-01, with the labels that each got.

#122 #120 - Added key and checksum to some events
  src/Tus/Server.php
  tests/Tus/ServerTest.php
Labels: need to check

#126 Add table of contents
  README.md
Labels: improvement

#128 Remove /bin/tus from export ignore
  .gitattributes
Labels: defect

#129 Some minor refactoring
  src/Cache/FileStore.php
  src/Commands/ExpirationCommand.php
  src/Request.php
  src/Tus/Server.php
  tests/Tus/ServerTest.php
Labels: improvement
