Repository ankitpokhrel/tus-php, pull requests merged in 2020-11, with the labels that each got.

#311 dev: Use official php docker image
  docker/base/Dockerfile
  docker/base/bin/xdebug.sh
  docker/base/configs/supervisord.conf
  docker/base/configs/www.conf
  docker/client/Dockerfile
  docker/client/configs/default.conf
  docker/server/Dockerfile
  docker/server/configs/default.conf
  docker/server/entrypoint.sh
Labels: dev/ci

#312 dev: Setup make
  .gitattributes
  Makefile
  README.md
  bin/build.sh
  bin/clean.sh
  bin/docker.sh
  bin/rebuild.sh
Labels: dev/ci

#313 dev: Add ability to switch seamlessly between PHP7 and PHP8
  Makefile
  docker/base/Dockerfile
  docker/base/bin/php-ext.sh
  docker/base/bin/xdebug.sh
  docker/base/configs/xdebug.2.ini
  docker/base/configs/xdebug.3.ini
Labels: dev/ci

#316 dev: Minor cleanup
  .gitattributes
  Dockerfile.client.k8s
  Dockerfile.server.k8s
  example/index.php
Labels: example

#317 dev: Use lowest supported PHP version in base image
  docker/base/Dockerfile
Labels: dev/ci

#307 PHP 8.0 Support
  .github/workflows/ci.yml
  .travis.yml
  composer.json
  docker/base/Dockerfile.php8
  tests/FileTest.php
  tests/ResponseTest.php
Labels: improvement

#320 dep(v1): Support guzzle 7
  .gitignore
  composer.json
Labels: dependencies

#324 handle Guzzle ClientException
  src/Tus/Client.php
  tests/Tus/ClientTest.php
Labels: client, defect
